import { 
  Activity,
  HeartPulse,
  Stethoscope,
  Bone,
  Dumbbell,
  Zap,
  Star,
  Shield,
  Award,
  CheckCircle,
  Users,
  Clock,
  Quote,
  HelpCircle,
  Lock,
  ShieldCheck,
  AlertCircle,
  MapPin,
  Calendar,
  Check,
  FileText,
  User,
  Phone,
  Mail,
  Home,
  Briefcase,
  GraduationCap,
  Heart,
  Eye,
  Settings,
  Search,
  Filter,
  Grid,
  List,
  Map,
  Navigation,
  Package,
  ShoppingCart,
  Tag,
  Truck,
  Wrench,
  Plus,
  Minus,
  ClipboardList,
  UserCheck,
  Video
} from "lucide-react";

// Helper function to map icon names to components
export const getIconComponent = (iconName: string) => {
  const iconMap: Record<string, any> = {
    ClipboardList: ClipboardList,
    UserCheck: UserCheck,
    Video: Video,
    Star: Star,
    Shield: Shield,
    Award: Award,
    CheckCircle: CheckCircle,
    Users: Users,
    Clock: Clock,
    Activity: Activity,
    HeartPulse: HeartPulse,
    Stethoscope: Stethoscope,
    Bone: Bone,
    Dumbbell: Dumbbell,
    Zap: Zap,
    Quote: Quote,
    HelpCircle: HelpCircle,
    Lock: Lock,
    ShieldCheck: ShieldCheck,
    AlertCircle: AlertCircle,
    MapPin: MapPin,
    Calendar: Calendar,
    Check: Check,
    FileText: FileText,
    User: User,
    Phone: Phone,
    Mail: Mail,
    Home: Home,
    Briefcase: Briefcase,
    GraduationCap: GraduationCap,
    Heart: Heart,
    Eye: Eye,
    Settings: Settings,
    Search: Search,
    Filter: Filter,
    Grid: Grid,
    List: List,
    Map: Map,
    Navigation: Navigation,
    Package: Package,
    ShoppingCart: ShoppingCart,
    Tag: Tag,
    Truck: Truck,
    Wrench: Wrench,
    Plus: Plus,
    Minus: Minus,
  };
  
  return iconMap[iconName] || Activity;
};